import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import AuthProvider from "./context/AuthContext";
=======
>>>>>>> 3fe75f2 (Connect db)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <AuthProvider>

=======
>>>>>>> 3fe75f2 (Connect db)
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
<<<<<<< HEAD
      </AuthProvider>
=======
>>>>>>> 3fe75f2 (Connect db)
    </html>
  );
}
